config/routes.rb
Rails.application.routes.draw do
  get '/tagged', to: "children#tagged", as: :tagged
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :children do
    resources :events, only: [:create]
  end
  resources :events, only: [:update, :destroy]
  resources :activities, only: [:show]
  resources :gifts, only: [:show]
end

app/controllers/children_controller.rb
class ChildrenController < ApplicationController
  before_action :set_children, only: [:show, :edit, :update, :destroy]
  before_action :activity_tagged, only: [:show]

  respond_to :html, :json, :js

  def index
    @children = policy_scope(Child).where(user: current_user)
    @events = Event.where(child: @child)
    @user = current_user
    @all_events = []
    @all_past_events = []

    @children.each do |child|
      child.events.each do |event|
        if event.start_date > Time.now
          @all_events << event
        end
      end
    end
    @children.each do |child|
      child.events.each do |event|
        if event.start_date < Time.now && event.photos.blank?
          @all_past_events << event
        end
      end
    end

  end

  def show
    authorize @child
    gift_query_search
    # @related_activities = @activities.find_related_tags
    @event_new = Event.new
    @events = Event.where(child: @child)
    if params[:event_id].present?
      @event = Event.find(params[:event_id])
    end
    @years = @child.events.map { |event| event.start_date.year }.uniq.sort.reverse
    activity_tagged
    map_geocode

    respond_to do |format|
      if params[:tag] || params[:query]
        format.json do
          render json: { activities: @activities,
                        json_markers: @markers,
                        tag: @tag }
                      end
        format.js { render partial: 'search_result.js.erb' }
      else
        format.html
      end
    end

  end

  def new
    @child = Child.new
    authorize @child
  end

  def create
    @child = Child.new(child_params)
    @child.user = current_user
    authorize @child
    if @child.save
      redirect_to children_path
    else
      render :new
    end
  end

  def edit
    authorize @child
  end

  def update
    @child.update(child_params)
    authorize @child
    if @child.valid?
      redirect_to child_path(@child)
    else
      render :edit
    end
  end

  def destroy
    @child.destroy
    authorize @child
    redirect_to children_path
  end

  private

  def set_children
    @child = Child.find(params[:id])
  end

  def child_params
    params.require(:child).permit(:first_name, :middle_name, :last_name, :birthday,
                                  :hobby, :parent, :photo, :tab, :gender, tag_list: [])
  end

  def map_geocode
    @markers = @activities.geocoded.map do |activity|
      {
        lat: activity.latitude,
        lng: activity.longitude,
        info_window: render_to_string(partial: "map_components/info_window", locals: { activity: activity }),
        id: activity.id
      }
    end
  end

  def gift_query_search
    if params[:query].present?
      @gifts = Gift.search_gifts(params[:query])
    else
      @gifts = Gift.all
    end
  end

  def activity_tagged
    if params[:tag].present?
      @tag = params[:tag]
      @activities = Activity.tagged_with(params[:tag])
    else
      @activities = Activity.all
    end
  end
end

app/views/children/_activities.html.erb
<% if params[:tab] == 'activities' %>
  <div data-controller="build-map" data-build='true' ></div>
<% end %>
<div class = "activity-tag" data-controller="actualize-tag">
  <div>
    <%= link_to 'All', child_path(@child, tab: 'activities'), class: "btn btn-primary tag-btn all-tag-btn" %>
    <% ActsAsTaggableOn::Tag.all.each do |tag| %>
      <%= link_to tag, child_path(@child, tab: 'activities', tag: tag.name), class: "btn btn-primary tag-btn", id:"tag-#{tag}",
                      data: {
                      action: 'click->actualize-tag#send'
                    } %>
    <% end %>
  </div>
  <%= render 'childcard', child: @child %>
</div>
<%= render './activity_components/activity_search_result', activities: @activities, child: @child %>

app/views/children/_activity_search_result.html.erb
<p class="search-result-text">There are <span class="count-result"><%= activities.count %></span> results</p>
<% if activities.count > 0 %>
  <div class="activity-container">
    <div class="row">
      <div class="col-12 col-md-4 col-lg-4" data-controller="activity-marker">
        <% activities.each do |activity| %>
          <%= link_to  activity_path(activity, child_id: child), data:{id: activity.id, action: 'mouseover->activity-marker#hover mouseout->activity-marker#hoverOut'} do %>
            <%= render './activity_components/activitycards', activity: activity %>
          <% end %>
        <% end %>
      </div>
      <div class="col-12 col-md-8 col-lg-8">
        <div id="map"
              style="width: 100%; height: 800px;"
              data-markers="<%= @markers.to_json %>"
              data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>
      </div>
    </div>
  </div>
<% else %>
  <h3 class="centered m-5"><i class="fas fa-sad-tear"></i> Please try another key word....</h3>
<% end %>

app/views/children/_add_photos_form.html.erb
<%= simple_form_for event, namespace: "event-#{event.id}" do |f| %>
  <%= f.input :photos, as: :file, input_html: { multiple: true, class: 'd-none',
  onChange: 'this.form.submit()' },
  label_html: { class: 'dashed-box'}, label: '📷 Upload'  %>
<% end %>

app/views/children/_calendar.html.erb
<%= month_calendar(events: @events) do |date, events| %>
  <% if events.length > 0 %>
    <% events.each do |event| %>
      <%# <% if event.start_date.strftime("%Y-%m-%d") >= Date.today.strftime("%Y-%m-%d") %>
      <div class="mark-date">
        <%= date.day %>
        <% break %>
      </div>
    <% end %>
  <% else %>
    <%= date.day %>
  <% end %>
<% end %>

app/views/children/_calendar_index.html.erb
<%= month_calendar(events: @all_events) do |date, events| %>
  <% if events.length > 0 %>
    <% events.each do |event| %>
      <%# <% if event.start_date.strftime("%Y-%m-%d") >= Date.today.strftime("%Y-%m-%d") %>
      <div class="mark-date">
        <%= date.day %>
        <% break %>
      </div>
    <% end %>
  <% else %>
    <%= date.day %>
  <% end %>
<% end %>

app/views/children/_cards.html.erb
<div class="card-trip h-100">
  <%# <%= link_to activity_path(activity), class: "card-link" do %>
    <% if activity.photo.attached? %>
      <%= cl_image_tag activity.photo.key, class: "main-image"%>
    <% else %>
      <%= image_tag 'camera-photo.png', class: 'main-image' %>
    <% end %>
    <div class="card-trip-infos">
      <div>
        <h2><%= activity.name.capitalize %></h2>
        <p>Address: <%= activity.address %></p>
      </div>
        <p class="card-trip-pricing">Price: <%= activity.price %>¥</p>
    </div>
  <%# <% end %>
</div>

app/views/children/_gift_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="exampleModalCenter-gift<%= gift.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">
        <% if gift.photo.attached? %>
          <%= cl_image_tag gift.photo.key, style: "width: 100%;"%>
        <% else %>
          <%= image_tag 'camera-photo.png', "width: 100%;"%>
        <% end %>
        </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          <h2><%= gift.name.capitalize %></h2>
          <p>Suggested Age Range: <%= gift.start_age %>-<%= gift.end_age %></p>
          <p>Price:<%= number_with_delimiter(gift.price, delimiter: ',') %></p>
          <p><%= gift.description %></p>
          <a href="<%= gift.website_link %>">Click to buy</a>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Connect to event</button>
      </div>
    </div>
  </div>
</div>

app/views/children/_history.html.erb
<div class="container-fluid" style="height=100%">
  <div class="row">
    <div class="col-12 col-md-3 col-lg-3 sidenav" style="overflow:auto">
      <div class="mt-5">
        <% if @child.photo.attached? %>
          <%= cl_image_tag @child.photo.key, class: "avatar-xlarge m-3"%>
        <% else %>
          <span class="m-3">
            <%= image_tag 'clock-image.png'%>
          </span>
        <%end %>
      </div>
      <div style="padding-top: 30px;">
        <h3 style="padding-bottom: 20px;"><strong><%= @child.first_name %></strong></h3>
        <p>Age: <%= @child.age(@child) %></p>
        <p>Birthday: <%= @child.birthday.strftime("%B %d, %Y") %></p>
        <p>Gender: <%= @child.gender %></p>
        <p>Hobby: <%= @child.hobby %></p>
      </div>
      <div style="padding-top: 30px">
        <%= month_calendar(events: @events) do |date, events| %>
          <%= date.day %>
          <% events.each do |event| %>
            <%# <% if event.start_date.strftime("%Y-%m-%d") >= Date.today.strftime("%Y-%m-%d") %>
            <%# <% end %>
            <div class="border-5 border-top border-danger">
            </div>
          <% end %>
        <% end %>
      </div>
      <div class="mb-4" style="padding-top: 50px">
        <p style="padding-bottom: 20px;"><strong>Create An Event</strong></p>
        <%= simple_form_for [@child, @event_new] do |f| %>
          <%= f.input :start_date,:label => "Date", as: :string, required: false, input_html: {class: "datepicker"}%>
          <%= f.input :occasion, as: :text %>
          <%= f.submit 'Create now!', class: 'btn btn-secondary my-3 px-5', style: "border-radius: 20px;" %>
        <% end %>
      </div>
    </div>
    <div class="col-12 col-md-9 col-lg-9">
    <ul class="nav tabs-underlined" id="myTab" role="tablist">
      <% @years.each_with_index do |year, index|  %>
        <li class="nav-item border-right" role="presentation">
          <a class="tab-underlined <%= "active" if params[:sub_tab].blank? && index.zero? || params[:sub_tab] == year.to_s %>" id="tab-<%= year %>" data-toggle="tab" href="#content-<%= year %>" role="tab" aria-controls="home" aria-selected="true"><%= year %></a>
        </li>
      <% end %>
    </ul>
    <div class="tab-content" id="myTabContent">
      <% @years.each_with_index do |year, index|  %>
        <div class="tab-pane fade py-3 <%= "show active" if params[:sub_tab].blank? && index.zero? || params[:sub_tab] == year.to_s %>" id="content-<%= year %>" role="tabpanel" aria-labelledby="tab-<%= year %>">
          <%= render "children/tabs", year: year %>
        </div>
      <% end %>
    </div>
    </div>
  </div>
</div>

app/views/children/_search.html.erb
<div id="search-result">
  <p class="search-result-text">There are <span class="count-result"><%= gifts.count %></span> results</p>
  <% if gifts.count.positive? %>
    <div class="gift-container">
      <div class="row">
        <% gifts.each do |gift| %>
          <div class="col-12 col-md-4 col-lg-3 py-2">
            <%= link_to  gift_path(gift, child_id: child) do %>
              <%= render './gift_components/giftcards', gift: gift %>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  <% else %>
    <h3 class="centered m-5"><i class="fas fa-sad-tear"></i> Please try another key word....</h3>
  <% end %>
</div>

app/views/children/_search_result.js.erb
document.getElementById('search-result').innerHTML ='<%= escape_javascript render(partial: 'search', locals: {gifts: @gifts, child: @child}) %>'

app/views/children/index.html.erb
<div class="index-child-container width-index">
  <div class="row">
    <div class="col-12 col-md-8 col-lg-8">
      <div class="container width-children-cards pt-3 mb-5">
        <h1 class='text-center index-h1'>Your children list</h1>
        <div class="d-flex justify-content-center">
          <a class="btn-child-show btn btn-primary my-1" href="/children/new"><span>Add Member <i class="fas fa-user-plus"></i></span></a>
        </div>
        <div class="row" >
          <% @children.each do |child| %>
            <div class="card-products my-4 col-12 col-md-5 col-lg-5">
              <% if child.photo.attached? %>
                <%= cl_image_tag child.photo.key%>
              <% else %>
                <%= image_tag "profile-photo1.png" %>
              <% end %>
              <div class="card-products-info child-relative">
                <h2 class=''><%= child.full_name %></h2>
                <div class="d-flex justify-content-between mt-2">
                  <div class ='pl-2'>
                    <div class="d-flex ">
                      <%= image_tag'family.png', class: 'image-tag-index p-1'%>
                      <p class=''><%= child.parent.capitalize %> </p>
                    </div>
                    <div class="d-flex pt-2">
                      <%= image_tag'jigsaw.png', class: 'image-tag-index mb-1 mr-1'%>
                      <% if child.tag_list.present? %>
                        <p class='mb-4'><%= child.tag_list.to_s.capitalize %></p>
                      <% else %>
                        <p class='mb-4'>None yet.</p>
                      <% end %>
                    </div>
                  </div>
                  <div class='align-right pr-2'>
                    <p> 🎂 <%= child.birthday %></p>
                    <p><%= child.age %></p>
                  </div>
                  <%= link_to "See more", child_path(child), class: "btn-small btn-primary p-2 position-absolute" %>
                  <%= link_to edit_child_path(child), child: child, class: 'edit-child' do%>
                    <i class="fas fa-user-edit"></i>
                  <% end %>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-10 col-md-4 col-lg-4 sidenav mx-auto calendar-height mb-5">
      <h4 class="mt-4 mb-3">Event Calendar</h4>
      <div class="mb-5" id="events_calendar_index" style="padding-top: 30px" >
        <%# <% @children.each do |child| %>
          <%# <% child.events.each do |event| %>
            <%# <% if event.start_date >  Time.now %>
            <%# <% @all_events << event %>
            <%# <% end %>
            <%# <% end %>
            <%# <% end %>
            <%= render partial: "calendar_index", locals: {events: @all_events} %>
          </div>
          <div class="mt-5 mb-5" style="text-align:left">
            <div class="container calendar-events">
              <h4 class="mb-4" style="text-align:center">Upcoming Events</h4>
              <div class="row " style='justify-content:center;'>
                <% @all_events.sort_by(&:start_date).each do |event|%>
                  <div class='d-flex justify-content-around align-items-center event-box text-center width-event col col-12 col-lg-5'>
                    <%= cl_image_tag event.child.photo.key, class: 'avatar' %>
                    <div class=''>
                      <p class='line-height text-center'><%= event.start_date.strftime("%B %d")%>,</p>
                      <p class='line-height text-center'><%= event.occasion.capitalize %>,</p>
                      <% unless event.gift.present? %>
                        Plan a 🎁 ?
                      <% end %>
                      <p class='line-height text-center'>Have fun!</p>
                    </div>
                  </div>
                <% end %>
              </div>
            </div>
            <div class=" container calendar-events pt-3">
              <h4 class="mb-4" style="text-align:center">Past event without photos</h4>
              <div class="row " style='justify-content:center;'>
                <% @all_past_events.sort_by(&:start_date).each do |event|%>
                  <div class='d-flex justify-content-around align-items-center event-box text-center width-event col col-12 col-lg-5'>
                    <%= cl_image_tag event.child.photo.key, class: 'avatar' %>
                    <div>
                      <p class='line-height'>⚠️</p>
                      <p class='line-height'><%= event.start_date.strftime("%B %d")%></p>
                      <p class='line-height'><%= event.child.first_name.capitalize %>'s <%= event.occasion.capitalize %></p>
                      <p class='line-height'>upload 📸 ?</p>
                    </div>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

app/views/children/index.js.erb
document.getElementById("events_calendar_index").innerHTML = "<%= escape_javascript render(partial: "calendar_index", locals: {events: @all_events}) %>" ;

app/views/children/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-5 col-sm-offset-4 mx-auto">
      <div class="form-login">
        <%= simple_form_for [@user, @child] do |f| %>
          <div class="d-flex justify-content-center align-items-center p-2">
            <div class="rounded-size">
              <%= image_tag "profile-photo1.png", class:"profile-image rounded-circle", id: "photo-preview"%>
            </div>
          </div>
          <%= f.input :photo, as: :file, input_html: { class: 'd-none', id: 'photo-input' },
            label_html: {class: "upload-photo" }, label: 'Upload Profile 📷 '  %>
          <%= f.input :first_name, class: 'mt-5' %>
          <%= f.input :middle_name, label: 'Middle name', placeholder: "optional" %>
          <%= f.input :last_name %>
          <%= f.input :parent, label: 'Parents' %>
          <%= f.input :birthday, html5: true, as: :date, label: "Date of Birth", start_year: Time.now.year - 15, end_year: Time.now.year, order:[ :year, :month, :day]%>
          <%= f.input :tag_list, as: :radio_buttons, label: 'Activity Preference (pick one)', collection: Child::TAGS, input_html: { class: "tag-selector"}, item_wrapper_class: 'tag-item' %>
          <%= f.submit 'Add', class: 'btn btn-success my-3 px-5', style: "border-radius: 20px;" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/children/show.html.erb
  <!-- app/views/offers/show.html.erb -->
<% content_for :meta_title, "#{@child.first_name.capitalize} is on #{DEFAULT_META["meta_product_name"]}" %>
<% content_for :meta_description, @child.age %>
<% if @child.photo.attached? %>
  <% content_for :meta_image, cl_image_path(@child.photo.key) %>
<% else %>
  <% content_for :meta_image, cl_image_path("http://res.cloudinary.com/dyyxuxymq/image/upload/mm6cyjjx011lc0s281clou5yb45q.jpg") %>
<% end %>
<ul class="nav tabs-underlined" id="myTab" role="tablist">
  <li class="nav-item" role="presentation">
    <a class="tab-underlined <%= "active" if params[:tab].nil? || params[:tab] ==  "event" %>" id="home-tab" data-toggle="tab" href="#event" role="tab" aria-controls="home" aria-selected="true">Events</a>
  </li>
  <li class="nav-item" role="presentation">
    <a class="tab-underlined <%= "active" if params[:tab] ==  "activities" %>" id="profile-tab" href="?tab=activities&tag=<%= @child.tag_list.first %>" role="tab" aria-controls="profile" aria-selected="false" data-controller="build-map" data-action='click->build-map#buildMap'>Activities</a>
  </li>
  <li class="nav-item" role="presentation">
    <a class="tab-underlined <%= "active" if params[:tab] ==  "gifts" %>" id="converstion-tab" data-toggle="tab" href="#gifts" role="tab" aria-controls="converstion" aria-selected="false">Gifts</a>
  </li>
</ul>
<div class="tab-content" id="myTabContent">
  <div class="tab-pane fade py-3 <%= "show active" if params[:tab].nil? || params[:tab] ==  "event" %>" id="event" role="tabpanel" aria-labelledby="home-tab">
    <%= render "children/events" %>
  </div>
  <div class="tab-pane fade py-3 <%= "show active" if params[:tab] ==  "activities"%>" id="activities" role="tabpanel" aria-labelledby="profile-tab">
    <%= render "children/activities" %>
  </div>
  <div class="tab-pane fade py-3 <%= "show active" if params[:tab] ==  "gifts"%>" id="gifts" role="tabpanel" aria-labelledby="converstion-tab">
    <%= render "children/gifts" %>
  </div>
</div>